### ISSUE TITLE
Trilha sonora QuebraDev

### ISSUE THREAD

**Issue by s4rd1nh4** [QuebraDev/quebradev.github.io#24]
Galera, 
Tem como disponibilizar a trilha sonora utilizada em alguma plataforma de streaming?

**Comment by miguelzinhe** [comment]
@s4rd1nh4 Tipo uma playlist ou o link das músicas? A gente pode fazer ambas as coisas via Spotify!

**Comment by onhernandes** [comment]
@s4rd1nh4 tirando as músicas de fundo, todas ficam disponíveis na página do episódio no site, mas não sei se todas estão disponíveis em serviços de streaming como o Spotify(algumas são bem antigas, etc).

cc @gucastiliao

**Comment by s4rd1nh4** [comment]
Playlist da musicas de fundo @miguelssrs

**Comment by gustavocstl** [comment]
@s4rd1nh4 as músicas de fundo geralmente são lo-fi, eu pego alguns e misturo pra gerar de acordo com a duração do episódio, mas não consigo mandar link pq não salvo hahaha

já as vírgulas ficam na descrição do episódio, mas também temos uma planilha pra organizar isso:
https://docs.google.com/spreadsheets/d/1a6652x4ORExFSFSY6GGVehhnr1FqpbCL7sxwi6fyCDQ

tem uma playlist que o @kteixeira criou no spotify com algumas músicas que já usamos tbm, mas tá um pouco desatualizada:
https://open.spotify.com/user/12171819159/playlist/5elYGbqkB0IoenZoWLftfD?si=sEG6z-z0TgGphR6FRtwB4w

**Comment by s4rd1nh4** [comment]
Obrigado @gucastiliao @miguelssrs @kteixeira , estes links ja sao uteis. @gucastiliao @miguelssrs @kteixeira
