### ISSUE TITLE
[SUGESTÃO] - Organização de arquivos

### ISSUE THREAD

**Issue by luan0ap** [QuebraDev/quebradev.github.io#6]
Seria interessante criar uma pasta para colocar as postagens, ficaria muito bagunçado deixar elas soltas assim na raiz do projeto. Se não me engano o hexo permite isso.

**Comment by reginaldojunior** [comment]
@gucastiliao ou @onhernandes manjam disso?

**Comment by onhernandes** [comment]
o @gucastiliao organizou no branch dev, não sei em que pé tá isso, mas tá usando hexo, que já organiza tudo direitinho. se pá já tá no ar mesmo.

**Comment by gustavocstl** [comment]
tá organizado na branch dev e a master fica somente o build do site pro github pages
lá tem a pasta [source/_posts](https://github.com/QuebraDev/quebradev.github.io/tree/dev/source/_posts) onde ficam todos os eps

**Comment by onhernandes** [comment]
![https://memegenerator.net/img/instances/81625162/aqui-tem-informao.jpg](https://memegenerator.net/img/instances/81625162/aqui-tem-informao.jpg)

**Comment by luan0ap** [comment]
Haha show galera, não tinha visto a branch dev ali
